spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyWishList
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: marumaru39
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
 
 
  thymeleaf:
    mode: "HTML"
  messages:
    basename: i18n/messages_ja, i18n/ValidationMessages_ja
    encoding: "UTF-8"
    fallback-to-system-locale: false
    